import { Ticker } from './Ticker/Ticker';

import style from './About.module.css';
import imageMobile from '../../image/about/mokeyImage.png';
import imageTablet from '../../image/about/mokeyImage2.png';
import imageDesktop from '../../image/about/mokeyImage3.png';
import cross from '../../image/svg/add-sharp.svg';

export const About = () => {
  return (
    <div id="about" className={style.about__container}>
      <div className={style.about__top_box}>
        <h1 className={style.about__title}>
          a Story that started with
          <span className={style.about__title_highlight}> one simple ape</span>
        </h1>

        <p className={style.about__text_secondTitle}>
          WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
          IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
        </p>
      </div>

      <div className={style.about__bottom_box}>
        <div className={style.about__textWrapper}>
          <img className={style.about__svgImage} src={cross} alt="cross" />
          <p className={style.about__text}>
            EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
            ARE RANDOMLY GENERATED BY USERS
          </p>
        </div>

        <picture>
          <source media="(max-width: 767px)" srcSet={imageMobile} />
          <source
            media="(min-width: 768px) and (max-width: 1279px)"
            srcSet={imageTablet}
          />
          <source media="(min-width: 1280px)" srcSet={imageDesktop} />
          <img src={imageDesktop} alt="Monkey" className={style.about__image} />
        </picture>
      </div>

      <Ticker />
    </div>
  );
};
